version: '3'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        image: eoglethorpe/natoolbox:djangoh-1.0
        command: ['./wait-for-it.sh', 'db:5432', '--', '/code/run_develop.sh']
        volumes:
            - .:/code
            - ./media:/media
        ports:
            - '8000:8000'
        depends_on:
            - db
