version: '3'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: "exit 0"
    nginx:
        build: ./deploy/nginx/
        image: eoglethorpe/natoolbox:nginxh-1.0
        ports:
            - '80:80'
        depends_on:
            - web
        volumes:
            - static-volume:/static
            - media-volume:/media
    web:
        build: .
        image: eoglethorpe/natoolbox:djangoh-1.0
        command: ['./wait-for-it.sh', 'db:5432', '--', '/code/run_production.sh']
        volumes:
            - static-volume:/static
            - media-volume:/media
        env_file:
            - production.env
        depends_on:
            - db

volumes:
    static-volume:
    media-volume:
