version: '3'

services:
    nginx:
        build: ./deploy/nginx/
        ports:
            - '80:80'
        depends_on:
            - web
        volumes:
            - app-volume:/code
            - static-volume:/static
    web:
        build: .
        image: natoolbox
        command: ['./run_production.sh']
        volumes:
            - app-volume:/code
            - static-volume:/static
        env_file:
            - production.env

volumes:
    app-volume:
    static-volume:
