version: '3'

services:
    db:
        image: postgres
        healthcheck:
            test: "exit 0"
    nginx:
        build: ./deploy/nginx/
        ports:
            - '80:80'
        depends_on:
            - web
        volumes:
            - app-volume:/code
            - static-volume:/static
    web:
        build: .
        image: natoolbox
        command: ['./wait-for-it.sh', 'db:5432', '--', 'bash', 'run_production.sh']
        volumes:
            - app-volume:/code
            - static-volume:/static
        depends_on:
            - db

volumes:
    app-volume:
    static-volume:
