# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(blank=True, choices=[('word', 'Word'), ('ppt', 'Powerpoint'), ('excel', 'Excel'), ('web', 'Webpage'), ('pdf', 'Pdf'), ('image', 'Image')], default=None, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.FileField(blank=True, default=None, null=True, upload_to='thumbnails')),
                ('fields', models.TextField(default='{}')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ToolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tool_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.ToolList'),
        ),
    ]
