# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0005_remove_tool_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='organization',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
