# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0007_tool_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.CharField(default='', max_length=10),
        ),
    ]
