# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0008_auto_20170808_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
