# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0009_auto_20170808_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
