# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0010_auto_20170809_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toollist',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='toollist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
