# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:11
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='downloadsection',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
