# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0002_auto_20170807_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='downloadsection',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='keylink',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
