# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0003_auto_20170807_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='background_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
