# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0004_introduction_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['title']},
        ),
    ]
