# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0005_auto_20170809_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('preview', models.FileField(blank=True, default=None, null=True, upload_to='highlight_previews')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='downloadsection',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='keylink',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='download',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='downloadsection',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='keylink',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
