# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0010_auto_20170909_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='section',
        ),
        migrations.AddField(
            model_name='downloadsection',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='downloads'),
        ),
        migrations.AddField(
            model_name='downloadsection',
            name='thumbnail',
            field=models.FileField(blank=True, default=None, null=True, upload_to='download_thumbnails'),
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
