# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0012_navlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
