# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0013_subscriber_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
