# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitySupport',
            new_name='SupportSector',
        ),
    ]
