# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_support', '0003_auto_20170910_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldSupport',
            new_name='FieldSupportRequest',
        ),
    ]
