# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_support', '0004_auto_20170910_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldsupportrequest',
            old_name='activity_support',
            new_name='support_sectors',
        ),
        migrations.RenameField(
            model_name='fieldsupportrequest',
            old_name='activity_support_other',
            new_name='support_sectors_other',
        ),
    ]
