# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_support', '0005_auto_20170910_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsupportrequest',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldsupportrequest',
            name='position',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
