# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_support', '0006_auto_20170919_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsupportrequest',
            name='situation_context_other',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name='fieldsupportrequest',
            name='service_requested',
        ),
        migrations.AddField(
            model_name='fieldsupportrequest',
            name='service_requested',
            field=models.ManyToManyField(blank=True, to='field_support.ServiceRequested'),
        ),
        migrations.AlterField(
            model_name='fieldsupportrequest',
            name='situation_context',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_support.SituationContext'),
        ),
    ]
